apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  webproxy: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
